### ISSUE TITLE
Make AppVeyor build publicily available

### ISSUE THREAD

**Issue by kichristensen** [mvno/Okanshi#83]
Currently only members of the mvno organization can see the build status, this makes it difficult to see what is wrong when a build fails.

**Comment by kichristensen** [comment]
This has hopefully be solved now, as I added a build outside the MVNO organization on AppVeyor

**Comment by kbilsted** [comment]
Reopen issue? I still cannot see the build problems in my latest PR

**Comment by kichristensen** [comment]
I think we need to add a other build server to the theater project, as there are no easy way two allow anonymous access as far as I can see. I'll create another issue for this, until I then I'll grant you access
